name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ubuntu:22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install ROS 2
      run: |
        apt update
        apt install -y curl gnupg lsb-release
        curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | apt-key add -
        echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2.list
        apt update
        apt install -y ros-humble-ros-base python3-colcon-common-extensions

    - name: Build
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --symlink-install

    - name: Test
      run: |
        bash src/mypkg/test/test.bash

